#!/bin/bash

#curl -i -X POST http://localhost:8080/counter/"$1" -d '{"id":"'"$1"'", "count": "'"$2"'"}'

curl -i -X POST https://focus-pottery-153219.appspot.com/counter/ -d '{"id":"'"$1"'", "count": "'"$2"'"}'
